name: Build and deploy beta.

on:
  push:
    branches: [ beta ]
    paths-ignore:
      - .github/**
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: helsingborg-stad/municipio-deploy/3.0@master
      with:
        deploy-host: ${{ secrets.DEPLOY_REMOTE_HOST_BETA_HELSINGBORG_SE }}
        deploy-host-path: ${{ secrets.DEPLOY_REMOTE_PATH_BETA_HELSINGBORG_SE }}
        deploy-host-backup-path: ${{ secrets.DEPLOY_REMOTE_BACKUP_DIR_BETA_HELSINGBORG_SE }}
        deploy-host-user: ${{ secrets.DEPLOY_REMOTE_USER }}
        deploy-host-user-key: ${{ secrets.DEPLOY_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        host-web-server-user: ${{ secrets.WEB_SERVER_USER }}
